title: music-maker
hero_image: images/banner.png
description: Design your own musical instrument.
version: 4
listed: false
copyedit: false
last_tested: "2021-06-11"
steps:
  - title: Introduction
  - title: Invent an instrument
  - title: How do you play it?
  - title: What does it sound like?
  - title: Create a Soundscape
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: Share
  - title: What next?

  