title: music-maker
hero_image: images/banner.png
description: music-maker description
version: 4
listed: false
copyedit: false
last_tested: "2021-06-11"
steps:
  - title: Introduction
  - title: Step title
  - title:
  - title: Share
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: What next?

  