---
title: Music maker
hero_image: images/banner.png
description: Design your own musical instrument.
meta_title: Scratch coding projects for kids and teens | Music maker
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Design your own Scratch musical instrument and experiment with sounds.
version: 4
listed: true
copyedit: true
last_tested: "2021-06-11"
steps:
  - 
    title: You will make
  - 
    title: Create an instrument
  - 
    title: Play music
    completion:
      - engaged
  - 
    title: Change the sound
  - 
    title: Create a soundscape
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 2
      passing_score: 2
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: Share
  - 
    title: What next?
